#ifndef _CALLBACKS_
#define _CALLBACKS_
#include <Fltkernel.h>
/* process access rights. is there a more appropriate header for this? */
#define PROCESS_CREATE_PROCESS 0x0080
#define PROCESS_CREATE_THREAD 0x0002
#define PROCESS_DUP_HANDLE 0x0040
#define PROCESS_TERMINATE 0x0001
#define PROCESS_VM_OPERATION 0x0008
#define PROCESS_VM_WRITE 0x0020
/* relax, these will be NOTted before ANDing with the ones passed in */
/* so set them naturally */
ACCESS_MASK PROCESS_DESIRED_ACCESS_MASK
= PROCESS_CREATE_PROCESS | PROCESS_CREATE_THREAD | PROCESS_DUP_HANDLE
  | PROCESS_TERMINATE | PROCESS_VM_OPERATION | PROCESS_VM_WRITE,
  PROCESS_ORIGINAL_ACCESS_MASK
  = PROCESS_CREATE_PROCESS | PROCESS_CREATE_THREAD | PROCESS_DUP_HANDLE
  | PROCESS_TERMINATE | PROCESS_VM_OPERATION | PROCESS_VM_WRITE;
#endif
